sudo: false
dist: trusty
language: ruby
cache:
  bundler: true
  directories:
    - vendor/bundle
    - tmp/rubocop_cache
script:
  - gem install colorize
  - bundle exec rails rubocop .
  - bundle exec rake test:setup
  - bundle exec rake test
branches:
  only:
    - master
